import { runCliContractChecks } from "./self-check/cli-contract.mjs";
import { runCredentialChecks } from "./self-check/credentials.mjs";
import { runEccRulesAndManifestChecks } from "./self-check/ecc-rules-and-manifest.mjs";
import { runEffortPickerChecks } from "./self-check/effort-picker.mjs";
import { runEccSourceAndTransactionChecks } from "./self-check/ecc-source-and-transaction.mjs";
import { runFilesystemChecks } from "./self-check/filesystem.mjs";
import { runGstackChecks } from "./self-check/gstack.mjs";
import { runGstackSafetyChecks } from "./self-check/gstack-safety.mjs";
import { runGstackPinnedSafetyChecks } from "./self-check/gstack-pinned-safety.mjs";
import { runGstackProvisionChecks } from "./self-check/gstack-provision.mjs";
import { runGeneratedAttributionHookChecks } from "./self-check/generated-attribution-hook.mjs";
import { runGitProgressChecks } from "./self-check/git-progress.mjs";
import { runMcpAndSettingsChecks } from "./self-check/mcp-and-settings.mjs";
import { runMcpInputFieldsChecks } from "./self-check/mcp-input-fields.mjs";
import { runMcpServerChecks } from "./self-check/mcp-servers.mjs";
import { runProvisionAndPipelineChecks } from "./self-check/provision-and-pipelines.mjs";
import { runProgressChecks } from "./self-check/progress.mjs";
import { runQualityGateChecks } from "./self-check/quality-gates.mjs";
import { runSetupWizardChecks } from "./self-check/setup-wizard.mjs";

await runGeneratedAttributionHookChecks(new URL("..", import.meta.url).pathname);
await runMcpAndSettingsChecks();
await (await import("./self-check/herdr.mjs")).runHerdrChecks();
await runMcpInputFieldsChecks();
await runMcpServerChecks();
await runEccRulesAndManifestChecks();
await runEffortPickerChecks();
await runEccSourceAndTransactionChecks();
await runCliContractChecks();
await runGstackChecks();
await (await import("./self-check/gstack-runtime.mjs")).runGstackRuntimeChecks();
await (await import("./self-check/gstack-diagnostics.mjs")).runGstackDiagnosticChecks();
await (await import("./self-check/coverage-cli.mjs")).runCoverageCliChecks();
await runGstackSafetyChecks();
await runGstackPinnedSafetyChecks();
await runProvisionAndPipelineChecks();
await runGstackProvisionChecks();
await runGitProgressChecks();
await runProgressChecks();
await runFilesystemChecks();
await runCredentialChecks();
await runQualityGateChecks();
await runSetupWizardChecks();

console.log("self-check passed");
